config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root  'static_pages#home'
  get  '/training_menu',to: 'static_pages#training_menu'
  get   '/signup',      to: 'users#new'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users
  resources :goal,              only: %i[edit update show]
  resources :threemonths_goals, only: %i[index show new create]
  resources :monthly_goals,     only: %i[index show new create]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @goal = Goal.all
    @threemonths_goals = ThreemonthsGoal
    .where(id: (ThreemonthsGoal.group(:quarter).select('max(id)')))
    .order('id': :asc)
    @monthly_goals = MonthlyGoal.all.order(id: "DESC").limit(1)
  end
  
  def goal
  end

  def threemonths_goal
  end

  def monthly_goal
  end

  def report
  end

  def training_menu
  end

  def participating_room
  end

  def like
  end

  def participationg_room_user
  end

  def message
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<h1>Achieve your goals</h1>
<div class="row">
<% @goal.each do |goal| %>
  <div class="col-md-8 col-md-offset-2">
    <%= link_to '今期目標', edit_goal_path(goal.id), method: :get , class: "btn" , id: "btn"%>
    <%= render partial: 'goal/goal', locals: {goal: @goal} %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= link_to '３ヶ月間目的', new_threemonths_goal_path(:id), method: :get , class: "btn" , id: "btn"%>
    <%= render template: "threemonths_goals/show"  %>
  </div>
</div>
<div class="row">
<% @monthly_goals.each do |monthly_goal| %>
  <div class="col-md-8 col-md-offset-2">
    <%= link_to '今月目的', new_monthly_goal_path(monthly_goal.id), method: :get , class: "btn" , id: "btn"%>
    <%= render template: "monthly_goals/show"  %>
    <% end %>
  </div>
</div>


<div id='hello_container'>
<app></app>
</div>

app/views/static_pages/training_menu.html.erb
<% provide(:title, "Training_menu") %>
<h1>トレーニング メニュー</h1>
<div class="lesson">
  <h2>＜距離走＞</h2>
  <p>これをやらなければマラソンは走れません。ペース設定を守って行うことでスタミナだけでなく走り続ける自力が身に付きます。<br>
      目的はAT（無酸素閾値）ペース向上、強度を保って２０km〜３０kmを走る。</p>
    <table border="1">
      <tr>
        <th>ターゲット<br>タイム</th><th>レースペース</th><th>距離走<br>目安ペース</th><th>頻度</th></tr>
      <tr>
        <td>サブ３</td><td>４分１５秒／km</td><td>４分３０秒〜<br>４分４５秒／km</td><td>２週間／回</td>
      </tr>
      <tr>
        <td>サブ３、１５</td><td>４分３７秒／km</td><td>４分５２秒〜<br>５分０７秒／km</td><td>２回／月</td>
      </tr>
      <tr>
        <td>サブ３、５</td><td>４分５８秒／km</td><td>５分１３秒〜<br>５分２８秒／km</td><td>１〜２回／月</td>
      </tr>
    </table>
  <h2>＜ミドル走＞</h2>
  <p>距離がこなせるようになったら取り入れる。より強度の高いポイント練習。イーブンペースで走り抜くことが大切。<br>
        距離走より少し早いペースで、距離走より短い距離１５〜２０kmを走る。</p>
    <table border="1">
      <tr>
        <th>ターゲット<br>タイム</th><th>レースペース</th><th>ミドル走<br>目安ペース</th><th>頻度</th></tr>
        <tr>
          <td>サブ３</td><td>４分１５秒／km</td><td>４分２０秒〜<br>４分２８秒／km</td><td>１回／週</td>
        </tr>
        <tr>
          <td>サブ３、１５</td><td>４分３７秒／km</td><td>４分４２秒〜<br>４分５０秒／km</td><td>１回／週</td>
        </tr>
        <tr>
          <td>サブ３、５</td><td>４分５８秒／km</td><td>５分０３秒〜<br>５分１１秒／km</td><td>１回／週</td>
      </tr>
    </table>
  <h2>＜ペース走＞</h2>
  <p>早いペースを維持して一定の処理を走ることで、心肺への刺激を入れつつ筋持久力向上するためのメニュー。<br>
          ペースの目安は５〜１０kmをイーブンで走れる限界ペース。</p>
    <table border="1">
        <tr>
          <th>ターゲット<br>タイム</th><th>レースペース</th><th>ペース走<br>目安ペース</th><th>頻度</th></tr>
          <tr>
            <td>サブ３</td><td>４分１５秒／km</td><td>３分５０秒〜<br>４分００秒／km</td><td>２週間／回</td>
          </tr>
          <tr>
            <td>サブ３、１５</td><td>４分３７秒／km</td><td>４分０５秒〜<br>４分１５秒／km</td><td>２週間／回</td>
          </tr>
          <tr>
            <td>サブ３、５</td><td>４分５８秒／km</td><td>４分２０秒〜<br>４分３０秒／km</td><td>３週間／回</td>
        </tr>
      </table>
      <h2>＜インターバル走＞</h2>
  <p>サブスリーにはスピード養成が不可欠。１回／週、インターバル走を取り入れて心肺機能と筋力の強化を図る。
    <br>やり方は１０００mのインターバル走なら５本がちょうど良いでしょう。１０００mの早いペースと２００m程度の<br>ジョグで繋ぐを繰り返しながら走る。全部同じペースか４〜５本目でペースを上げられるように意識しましょう。
  </p>
  <table border="1">
    <tr>
      <th>ターゲット<br>タイム</th><th>レースペース</th><th>インターバル走<br>目安ペース</th><th>頻度</th></tr>
        <tr>
        <td>サブ３</td><td>４分１５秒／km</td><td>１０００m × ５本<br>３分５０秒以内<br>or<br>２０００m × ３本<br>８分００秒以内</td><td>１回／週</td>
        </tr>
        <tr>
          <td>サブ３、１５</td><td>４分３７秒／km</td><td>１０００m × ５本<br>４分００秒以内<br>or<br>２０００m × ２本<br>８分２０秒以内</td><td>２週間／回</td>
        </tr>
        <tr>
          <td>サブ３、５</td><td>４分５８秒／km</td><td>１０００m<br> × ３〜５本<br>４分１５秒以内</td><td>２週間／回</td>
      </tr>
    </table>
</div>