config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root  'static_pages#home'
  get  '/training_menu',to: 'static_pages#training_menu'
  get   '/signup',      to: 'users#new'
  get    '/login',      to: 'sessions#new'
  post   '/login',      to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users
  resources :goal,              only: %i[edit update show]
  resources :threemonths_goals, only: %i[index show new create]
  resources :monthly_goals,     only: %i[index show new create]
end

app/models/threemonths_goal.rb
class ThreemonthsGoal < ApplicationRecord
  belongs_to :user, optional: true
  validates :user_id, presence: true    #空の値ではないこと
  validates :content, presence: true, length: { maximum: 140 }
  attr_accessor :collection
end

app/controllers/threemonths_goals_controller.rb
class ThreemonthsGoalsController < ApplicationController
  
  def new
    @form = Form::ThreemonthsGoalCollection.new
  end

  def create
    quarter_0 = ThreemonthsGoal.new(content:params[:form_threemonths_goal_collection][:content_1], quarter: 0,user_id: current_user.id)
    quarter_1 = ThreemonthsGoal.new(content:params[:form_threemonths_goal_collection][:content_2], quarter: 1,user_id: current_user.id)
    quarter_2 = ThreemonthsGoal.new(content:params[:form_threemonths_goal_collection][:content_3], quarter: 2,user_id: current_user.id)
    quarter_3 = ThreemonthsGoal.new(content:params[:form_threemonths_goal_collection][:content_4], quarter: 3,user_id: current_user.id)
    #@form = Form::ThreemonthsGoalCollection.new(threemonths_goal_collection_params)

    #if @form.save
    if quarter_0.save && quarter_1.save && quarter_2.save && quarter_3.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def index
    @threemonths_goals = ThreemonthsGoal.all
  end
  
  def show
    @threemonths_goals = ThreemonthsGoal.all
  end

  private
  def threemonths_goal_collection_params
    params
      .require(:form_threemonths_goal_collection)
      .permit(:content_1,:content_2,:content_3,:content_4)
  end
end

app/helpers/threemonths_goals_helper.rb
module ThreemonthsGoalsHelper
end

app/views/threemonths_goals/new.html.erb
<% provide(:title, 'creat threemonths_goal') %>
<% provide(:button, '作成') %>
<h1>３ヶ月ごとの目標</h1>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <%= form_with model: @form ,url: threemonths_goals_path, local: true  do |f| %>
    <%= f.label :１〜３月 %>
    <%= f.text_field :content_1 %>
    <%= f.label :４〜６月 %>
    <%= f.text_field :content_2 %>
    <%= f.label :７〜９月 %>
    <%= f.text_field :content_3 %>
    <%= f.label :１０〜１２月 %>
    <%= f.text_field :content_4 %>
    <%= f.submit "Submit" %>
  <% end %>
  </div>
  <div class="col-md-1 col-md-offset-1">
    <%= link_to "キャンセル", root_path , class: "btn" , id: "cancel" %>
  </div>
</div>

app/views/threemonths_goals/show.html.erb
<% @threemonths_goals.each do |i| %>
  <td>
  <% if i.quarter === 0 %>
    <p>１〜３月 = <%= i.content %></p>
  <% elsif i.quarter === 1 %>
    <p>４〜６月 = <%= i.content %></p>
  <% elsif i.quarter === 2 %>
    <p>７〜９月 = <%= i.content %></p>
  <% else i.quarter === 3 %>
    <p>１０〜１２月 = <%= i.content %></p>
  <% end %>
  </td>
<% end %>